apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storageclass
provisioner: k8s-sigs.io/local-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
